[package]
name = "tideorm-macros"
version = "0.9.16"
edition = "2024"
description = "Procedural macros for TideORM"
license = "MIT"
repository = "https://github.com/mohamadzoh/tideorm"
homepage = "https://tideorm.com"
readme = "README.md"
rust-version = "1.85"
exclude = ["tests/**"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.105"
quote = "1.0.43"
syn = { version = "2.0.114", features = ["full", "extra-traits", "parsing"] }
darling = "0.23.0"
convert_case = "0.11.0"
