use async_trait::async_trait;
use std::collections::HashMap;

use crate::error::{Error, Result};
use crate::query::QueryBuilder;

#[cfg(feature = "dirty-tracking")]
use super::dirty_tracking;
use super::{BatchUpdateBuilder, OnConflictBuilder, crud, serialization};

/// Core trait for TideORM models
///
/// This trait exposes the CRUD and query entry points generated by TideORM's
/// model macros.
///
/// Methods use the global database handle configured during startup, so if
/// model calls fail before reaching SQL execution, verify that `TideConfig`
/// finished connecting successfully.
#[async_trait]
pub trait Model:
    super::ModelMeta
    + crate::internal::InternalModel
    + crate::validation::Validate
    + serde::Serialize
    + for<'de> serde::Deserialize<'de>
{
    /// Get the primary key value of this instance
    fn primary_key(&self) -> Self::PrimaryKey;

    /// Load every row of this model's table.
    ///
    /// Soft-deleted rows are excluded. There is no limit and no streaming — the
    /// whole table is materialised in memory, so use [`Model::query`] with a
    /// filter or [`Model::paginate`] for anything that can grow.
    async fn all() -> Result<Vec<Self>> {
        crate::internal::QueryExecutor::find_all::<Self>().await
    }

    /// Start a query for this model.
    ///
    /// This is the general entry point: filters, ordering, joins, aggregates,
    /// and bulk deletes all hang off the returned builder, and soft-deleted rows
    /// are scoped out unless `with_trashed()` asks for them. Reach for
    /// [`Model::all`], [`Model::first`], or [`Model::find`] only when the query
    /// really is that simple.
    ///
    /// The query runs against whichever connection is current when a terminal
    /// method is awaited, so a builder created outside a transaction still joins
    /// one if it is awaited inside the transaction closure.
    fn query() -> QueryBuilder<Self> {
        QueryBuilder::new()
    }

    /// Start a query pinned to a specific database handle.
    ///
    /// Use this for a replica, a second tenant database, or any case where the
    /// global connection is not the one that should serve the query.
    ///
    /// **An ambient transaction still wins.** Inside
    /// `Database::transaction(..)` every query runs on the transaction's
    /// connection, including one pinned with `query_with`, because that is what
    /// makes a plain `Model::find()` inside the closure join the transaction at
    /// all. Rendering follows execution, so the SQL is at least built for the
    /// backend it actually reaches. Run replica reads outside the transaction if
    /// you need them to go to the replica.
    fn query_with(db: &crate::database::Database) -> QueryBuilder<Self> {
        QueryBuilder::new().with_database(db.clone())
    }

    /// Count the rows of this model's table.
    ///
    /// Soft-deleted rows are not counted. Counts the whole table; for a filtered
    /// count use `Model::query().where_eq(..).count()`.
    async fn count() -> Result<u64> {
        crate::internal::QueryExecutor::count::<Self>().await
    }

    /// Delete **every** row of this model's table.
    ///
    /// A `DELETE` with no `WHERE` clause, run without per-row callbacks; on a
    /// soft-delete model it marks every live row deleted instead, and
    /// `Model::query().only_trashed().force_delete()` empties the trash. It
    /// exists as a deliberate escape hatch precisely because the ordinary bulk
    /// paths refuse to run without a filter. Returns the number of rows it
    /// deleted or marked.
    async fn delete_all() -> Result<u64> {
        Self::query().delete_all().await
    }

    /// Return whether the table holds at least one row.
    ///
    /// Cheaper than [`Model::count`] on a large table: the statement stops at
    /// the first row instead of scanning to produce an exact total.
    async fn exists_any() -> Result<bool> {
        crate::internal::QueryExecutor::exists_any::<Self>().await
    }

    /// Insert multiple records and return the inserted models.
    ///
    /// Every model is checked against its validation rules first, and nothing
    /// is written unless all of them pass. No callbacks run, `before_validation`
    /// included, so each model is validated as it was built.
    ///
    /// TideORM uses the most efficient strategy the active backend supports.
    /// PostgreSQL and SQLite send a batch `INSERT ... RETURNING`. MySQL and
    /// MariaDB batch models that set their own integer or `Uuid` key and read
    /// them back with one `SELECT`, and insert other models one at a time, so
    /// database-generated fields such as auto-incremented IDs are still
    /// reflected in the result.
    async fn insert_all(models: Vec<Self>) -> Result<Vec<Self>>
    where
        <<Self as crate::internal::InternalModel>::Entity as crate::internal::EntityTrait>::Model:
            crate::internal::IntoActiveModel<<Self as crate::internal::InternalModel>::ActiveModel>,
    {
        crud::insert_all::<Self>(models).await
    }

    /// Insert a record, updating it instead when it collides on `conflict_columns`.
    ///
    /// `conflict_columns` must be covered by a unique constraint or unique index
    /// — the database, not TideORM, decides what counts as a conflict. Every
    /// non-conflict column is overwritten except a managed `created_at`, which
    /// keeps the stored row's creation time; use [`Model::on_conflict`] when only
    /// some of them should be.
    async fn insert_or_update(model: Self, conflict_columns: Vec<&str>) -> Result<Self> {
        let conflict_columns = conflict_columns.into_iter().map(str::to_string).collect();
        Self::__insert_with_conflict(model, OnConflictBuilder::new(conflict_columns)).await
    }

    /// Start an upsert whose conflict behaviour you want to narrow.
    ///
    /// The long form of [`Model::insert_or_update`]: the returned builder can
    /// restrict which columns the update writes, which is how insert-only
    /// columns are protected.
    fn on_conflict(conflict_columns: Vec<&str>) -> OnConflictBuilder<Self> {
        OnConflictBuilder::new(
            conflict_columns
                .into_iter()
                .map(|s| s.to_string())
                .collect(),
        )
    }

    /// Start a filtered bulk `UPDATE`.
    ///
    /// The returned builder requires at least one explicit filter and, like
    /// [`Model::query`], leaves soft-deleted rows out; call
    /// [`BatchUpdateBuilder::with_trashed`] for a backfill that reaches them.
    fn update_all() -> BatchUpdateBuilder<Self> {
        BatchUpdateBuilder::new()
    }

    /// Run `f` inside a database transaction, committing when it returns `Ok`.
    ///
    /// The transaction is installed as the ambient connection for the duration
    /// of the closure, so plain calls such as `User::find(id)` or
    /// `Post::query().get()` inside it join the transaction without being handed
    /// a handle. A nested call opens a savepoint rather than a second
    /// transaction.
    ///
    /// The handle must not outlive the closure: commit fails with "transaction
    /// handle leaked outside the transaction scope" if a clone escaped. Any
    /// `Err` return rolls back.
    ///
    /// The receiver type is incidental — this does not scope the transaction to
    /// one model. `Database::transaction` is the same operation spelled without
    /// an arbitrary model in front of it.
    async fn transaction<F, T>(f: F) -> Result<T>
    where
        F: for<'c> FnOnce(
                &'c crate::database::Transaction,
            ) -> std::pin::Pin<
                Box<dyn std::future::Future<Output = Result<T>> + Send + 'c>,
            > + Send,
        T: Send,
    {
        crud::transaction(f).await
    }

    /// Return one row of this model's table, or `None` when it is empty.
    ///
    /// No `ORDER BY` is applied, so "first" means whichever row the database
    /// hands back first — not the oldest or the lowest primary key. Add an
    /// explicit order with `Model::query().order_asc(..).first()` when the
    /// choice matters. Soft-deleted rows are excluded.
    async fn first() -> Result<Option<Self>> {
        crate::internal::QueryExecutor::first::<Self>().await
    }

    /// Return the row with the highest primary key, or `None` when the table is empty.
    ///
    /// Unlike [`Model::first`] this is ordered: the primary key columns are
    /// sorted descending. For an auto-increment key that is the most recently
    /// inserted row, but for a natural or UUID key it is simply the largest one.
    /// Soft-deleted rows are excluded.
    async fn last() -> Result<Option<Self>> {
        crate::internal::QueryExecutor::last::<Self>().await
    }

    /// Return one page of models using 1-based page numbers.
    ///
    /// Rows are ordered by primary key, so walking the pages visits each row
    /// once even while rows are updated in between. For another order, use
    /// `Model::query().order_asc(..).page(page, per_page)`.
    ///
    /// Returns a validation error when `page == 0` or `per_page == 0`, or when
    /// `per_page` or the page's offset is past `i64::MAX`.
    async fn paginate(page: u64, per_page: u64) -> Result<Vec<Self>> {
        crate::internal::QueryExecutor::paginate::<Self>(page, per_page).await
    }

    /// Look up a record by primary key.
    ///
    /// On a soft-delete model a trashed row is not found, as it is not by any
    /// other read; `Model::query().with_trashed().find(id)` reads one, to
    /// inspect or restore it.
    async fn find(id: Self::PrimaryKey) -> Result<Option<Self>>;

    /// Look up a record by primary key on a specific database handle.
    ///
    /// The handle-pinned counterpart of [`Model::find`], for replicas or
    /// per-tenant connections; it shares the same soft-delete behaviour.
    async fn find_with(
        id: Self::PrimaryKey,
        db: &crate::database::Database,
    ) -> Result<Option<Self>>;

    /// Look up a record by primary key, returning a not-found error when it is
    /// missing, as [`Model::find`] reads it.
    async fn find_or_fail(id: Self::PrimaryKey) -> Result<Self> {
        let id_display = Self::primary_key_display(&id);
        Self::find(id).await?.ok_or_else(|| {
            Error::not_found(format!(
                "{} with {} not found",
                Self::table_name(),
                id_display
            ))
        })
    }

    /// Return whether a record with this primary key exists.
    ///
    /// Soft-delete-enabled models report trashed rows as not existing, matching
    /// `all()`, `count()`, and `query()`.
    async fn exists(id: Self::PrimaryKey) -> Result<bool> {
        Ok(Self::find(id).await?.is_some())
    }

    /// Insert a new record.
    ///
    /// This always performs an `INSERT`. To get create-or-update behavior,
    /// use `save()` instead.
    async fn create(model: Self) -> Result<Self>;

    /// Delete the record with this primary key.
    ///
    /// The row is loaded and handed to [`Model::delete`], so its callbacks run
    /// and a soft-delete model is marked rather than removed. Returns `Ok(0)`
    /// when no such row exists, or when it is already trashed.
    async fn destroy(id: Self::PrimaryKey) -> Result<u64> {
        // Load the row first so `destroy(id)` runs the same delete, and the
        // same callbacks, as `delete(self)`; a trashed row is not found.
        match Self::find(id).await? {
            Some(model) => model.delete().await,
            None => Ok(0),
        }
    }

    /// Persist this model.
    ///
    /// Performs an `INSERT` when `is_new()` returns true, otherwise performs
    /// an `UPDATE` for the current primary key.
    async fn save(self) -> Result<Self> {
        if self.is_new() {
            return Self::create(self).await;
        }
        // The row-presence probe counts trashed rows: saving over a trashed
        // natural-key row must UPDATE it, not INSERT into a conflict with it.
        let single_counter_key =
            Self::primary_key_auto_increment() && Self::primary_key_names().len() == 1;
        if single_counter_key
            || super::__exists_including_trashed::<Self>(&self.primary_key()).await?
        {
            self.update().await
        } else {
            Self::create(self).await
        }
    }

    /// Update an existing record.
    ///
    /// This always performs an `UPDATE` using the model's current primary key.
    async fn update(self) -> Result<Self>;

    /// Delete this record's row.
    ///
    /// On a soft-delete model the row is marked deleted, as
    /// `SoftDelete::soft_delete` marks it; `SoftDelete::force_delete` removes it
    /// for good. Runs the delete callbacks and returns the number of rows
    /// deleted, which is `0` if the row was already gone or trashed.
    async fn delete(self) -> Result<u64>;

    /// Remove this record's row for good, even on a soft-delete model, running
    /// the delete callbacks. `SoftDelete::force_delete` calls it.
    #[doc(hidden)]
    async fn __force_delete(self) -> Result<u64>;

    #[doc(hidden)]
    async fn __insert_with_conflict(model: Self, builder: OnConflictBuilder<Self>) -> Result<Self>;

    /// Re-read this record from the database and return the fresh copy.
    ///
    /// Returns a new value rather than mutating in place, so the stale one stays
    /// available for comparison. Errors with a not-found error when the row has
    /// been deleted in the meantime. Unlike [`Model::find`], it still reads a
    /// soft-deleted row: the record in hand is the one to refresh.
    async fn reload(&self) -> Result<Self> {
        crud::reload(self).await
    }

    /// Return whether this model should be treated as not yet persisted.
    ///
    /// `save()` uses this to decide between `INSERT` and `UPDATE`.
    fn is_new(&self) -> bool {
        crud::is_new(self)
    }

    /// Return the persisted field names whose values differ from the last snapshot
    /// TideORM loaded or saved for this model.
    ///
    /// # Missing baseline versus no changes
    ///
    /// The outer `Option` reports whether there was anything to compare against:
    ///
    /// - `Ok(None)` — no baseline. A model built by hand, rebuilt from JSON, or
    ///   whose baseline was evicted from the bounded snapshot store cannot say
    ///   which fields differ from the row on disk.
    /// - `Ok(Some(fields))` — a baseline exists, and `fields` lists exactly what
    ///   changed. An empty vector here really does mean "nothing changed".
    ///
    /// That makes the "skip the write when nothing changed" gate explicit about
    /// the unknown case instead of silently swallowing it:
    ///
    /// ```ignore
    /// match model.changed_fields()? {
    ///     // Nothing to compare against: save rather than guess.
    ///     None => model.save().await?,
    ///     Some(changed) if !changed.is_empty() => model.save().await?,
    ///     Some(_) => model,
    /// };
    /// ```
    #[cfg(feature = "dirty-tracking")]
    fn changed_fields(&self) -> Result<Option<Vec<&'static str>>> {
        dirty_tracking::changed_fields(self)
    }

    /// Return one persisted field's original value from the last snapshot TideORM
    /// loaded or saved for this model.
    ///
    /// Accepts either the Rust field name or the database column name.
    ///
    /// The two `Option`s answer two different questions, matching
    /// [`Model::changed_fields`]:
    ///
    /// - `Ok(None)` — no baseline exists, so no original value is known.
    /// - `Ok(Some(None))` — a baseline exists but held no value for this field.
    /// - `Ok(Some(Some(value)))` — the remembered value.
    ///
    /// Returns an error when `field` names neither a field nor a column of this
    /// model, whether or not a baseline exists.
    #[cfg(feature = "dirty-tracking")]
    fn original_value(&self, field: &str) -> Result<Option<Option<serde_json::Value>>> {
        dirty_tracking::original_value(self, field)
    }

    /// Render this model as JSON for an API response.
    ///
    /// This is not plain `serde_json::to_value`: hidden attributes (the model's
    /// own plus the global ones from `Config`) are dropped, attachment fields are
    /// expanded into URLs, and translatable fields are resolved to one language.
    /// One option key is understood: `"language"` picks the translation to emit
    /// (default: the model's fallback language).
    ///
    /// Serialization failures are logged and yield `{}` rather than an error,
    /// for compatibility. Use [`Model::try_to_json`] to handle failures explicitly.
    fn to_json(&self, options: Option<HashMap<String, String>>) -> serde_json::Value {
        serialization::to_json::<Self>(self, options.as_ref())
    }

    /// Render JSON while reporting serialization or translation decoding errors.
    fn try_to_json(&self, options: Option<HashMap<String, String>>) -> Result<serde_json::Value> {
        serialization::try_to_json::<Self>(self, options.as_ref())
    }

    /// Render a collection, failing if any model cannot be serialized.
    fn try_collection_to_json(
        models: Vec<Self>,
        options: Option<HashMap<String, String>>,
    ) -> Result<serde_json::Value> {
        models
            .iter()
            .map(|model| serialization::try_to_json(model, options.as_ref()))
            .collect::<Result<Vec<_>>>()
            .map(serde_json::Value::Array)
    }

    /// Render a list of models as a JSON array, applying [`Model::to_json`] to each.
    ///
    /// The same options apply to every element, so one language is used across
    /// the collection.
    fn collection_to_json(
        models: Vec<Self>,
        options: Option<HashMap<String, String>>,
    ) -> serde_json::Value {
        serialization::collection_to_json::<Self>(models, options)
    }

    /// Flatten this model into string key/value pairs.
    ///
    /// Built on [`Model::to_json`] with no options, so hidden attributes stay
    /// hidden. Every value is stringified — numbers and booleans become their
    /// text form, `null` becomes `"null"`, and nested objects and arrays become
    /// their JSON text. Intended for template context and form population, not
    /// for round-tripping back into a model.
    fn to_hash_map(&self) -> HashMap<String, String> {
        serialization::to_hash_map::<Self>(self)
    }
}
