use super::*;
use crate::migration::TableBuilder;

/// The SQL type sync would give a column of `rust_type` on `backend`.
fn sync_column_type(rust_type: &str, backend: Backend) -> String {
    let column = ColumnDef::new("value", rust_type);
    column_definition(&column, column_type(&column), false)
        .column_type
        .to_sql(backend.as_database_type())
}

#[test]
fn sync_renders_the_shared_rust_type_table() {
    // The one thing this test really pins: sync must not carry its own opinion
    // about what a Rust type becomes. Whatever `rust_type_to_column_type` says,
    // rendered for the backend, is what the column gets.
    for rust_type in [
        "i64",
        "u8",
        "u16",
        "u32",
        "u64",
        "Option<u16>",
        "i128",
        "Decimal",
        "rust_decimal::Decimal",
        "String",
        "Uuid",
        "NaiveDateTime",
        "chrono::NaiveDateTime",
        "Option<NaiveDateTime>",
        "DateTime<Utc>",
        "chrono::DateTime<chrono::Utc>",
        "NaiveDate",
        "NaiveTime",
        "Vec<u8>",
        "Vec<String>",
        "serde_json::Value",
        "bool",
    ] {
        for backend in [Backend::Postgres, Backend::MySql, Backend::Sqlite] {
            let expected = rust_type_to_column_type(rust_type)
                .expect("mapped type")
                .to_sql(backend.as_database_type());
            assert_eq!(
                sync_column_type(rust_type, backend),
                expected,
                "sync disagreed with the shared mapping for '{rust_type}' on {backend:?}"
            );
        }
    }
}

#[test]
fn a_synced_table_matches_the_migration_that_declares_it() {
    // Sync used to render through sea-query, which spells an auto-increment
    // key `GENERATED BY DEFAULT AS IDENTITY` on PostgreSQL and `AUTOINCREMENT`
    // on SQLite, while migrations emit `BIGSERIAL` and a rowid key - so the
    // same declaration built a different table depending on the path.
    let model = ModelSchema::new("users")
        .schema("")
        .primary_keys(vec!["id".to_string()])
        .column(ColumnDef::new("id", "i64").primary_key().auto_increment())
        .column(ColumnDef::new("email", "String").not_null())
        .column(ColumnDef::new("age", "Option<i32>"))
        .column(ColumnDef::new("active", "bool").not_null().default("TRUE"));

    for backend in [Backend::Postgres, Backend::MySql, Backend::Sqlite] {
        let mut table = TableBuilder::new("users", backend.as_database_type());
        table.id();
        table.text("email").not_null();
        table.integer("age");
        table.boolean("active").not_null().default(true);

        assert_eq!(
            build_create_table_sql(&model, backend),
            table.build_create(true),
            "sync and migrations disagree on {backend:?}"
        );
    }
}

#[test]
fn auto_increment_keys_keep_the_width_the_plain_column_would_get() {
    // A u32 key widened to BIGSERIAL is unreadable into a u32 on PostgreSQL,
    // and disagrees with the INTEGER a plain u32 column gets. The serial type
    // has to match the width the plain column renders at.
    for (rust_type, serial) in [
        ("i64", "BIGSERIAL"),
        ("u64", "BIGSERIAL"),
        ("i32", "SERIAL"),
        ("u32", "SERIAL"),
        ("i16", "SMALLSERIAL"),
        ("u8", "SMALLSERIAL"),
    ] {
        let model = ModelSchema::new("counters").schema("").column(
            ColumnDef::new("id", rust_type)
                .primary_key()
                .auto_increment(),
        );

        let sql = build_create_table_sql(&model, Backend::Postgres);
        assert!(
            sql.contains(&format!("\"id\" {serial}")),
            "'{rust_type}' key should render as {serial}. Got: {sql}"
        );
    }
}

#[test]
fn create_table_never_emits_auto_increment_for_a_non_integer_key() {
    let model = ModelSchema::new("users")
        .schema("")
        .column(ColumnDef::new("id", "Uuid").primary_key().auto_increment());

    let postgres = build_create_table_sql(&model, Backend::Postgres);
    assert!(postgres.contains("\"id\" UUID"), "Got: {}", postgres);
    assert!(
        !postgres.to_uppercase().contains("SERIAL"),
        "Got: {}",
        postgres
    );

    let mysql = build_create_table_sql(&model, Backend::MySql);
    assert!(!mysql.contains("AUTO_INCREMENT"), "Got: {}", mysql);
}

#[test]
fn composite_keys_are_a_table_constraint_and_keep_their_not_null() {
    // SQLite does not imply NOT NULL for the columns of a composite key.
    let model = ModelSchema::new("user_roles")
        .schema("")
        .primary_keys(vec!["user_id".to_string(), "role_id".to_string()])
        .column(ColumnDef::new("user_id", "i64").primary_key())
        .column(ColumnDef::new("role_id", "i64").primary_key());

    let sql = build_create_table_sql(&model, Backend::Sqlite);
    assert!(sql.contains("\"user_id\" INTEGER NOT NULL"), "Got: {}", sql);
    assert!(sql.contains("\"role_id\" INTEGER NOT NULL"), "Got: {}", sql);
    assert!(
        sql.contains("PRIMARY KEY (\"user_id\", \"role_id\")"),
        "Got: {}",
        sql
    );
}

#[test]
fn create_table_targets_the_schema_the_model_declares() {
    let model = ModelSchema::new("users")
        .schema("tenant_a")
        .column(ColumnDef::new("id", "i64").primary_key());

    // The existence probe and the force DROP both filter on `schema_name`, so
    // CREATE TABLE has to name the same schema or every run recreates the table
    // somewhere neither of them looks.
    let postgres = build_create_table_sql(&model, Backend::Postgres);
    assert!(
        postgres.contains("\"tenant_a\".\"users\""),
        "CREATE TABLE must name the schema the model declares. Got: {}",
        postgres
    );

    // MySQL's schema is a database, which the model's queries name too; SQLite
    // has none.
    let mysql = build_create_table_sql(&model, Backend::MySql);
    assert!(mysql.contains("`tenant_a`.`users`"), "Got: {}", mysql);

    let sqlite = build_create_table_sql(&model, Backend::Sqlite);
    assert!(!sqlite.contains("tenant_a"), "Got: {}", sqlite);
}

#[test]
fn qualifying_schema_follows_what_the_model_declared() {
    let pg = Backend::Postgres;
    let model = ModelSchema::new("users").schema("tenant_a");
    assert_eq!(qualifying_schema(&model, pg), Some("tenant_a"));
    assert_eq!(qualifying_schema(&model, Backend::MySql), Some("tenant_a"));
    assert_eq!(qualifying_schema(&model, Backend::Sqlite), None);

    // Undeclared: PostgreSQL's `public`, and MySQL's connected database.
    let undeclared = ModelSchema::new("users");
    assert_eq!(qualifying_schema(&undeclared, pg), Some("public"));
    assert_eq!(qualifying_schema(&undeclared, Backend::MySql), None);

    let unqualified = ModelSchema::new("users").schema("");
    assert_eq!(qualifying_schema(&unqualified, pg), None);
    assert_eq!(qualifying_schema(&unqualified, Backend::MySql), None);
}

#[test]
fn column_diff_reports_missing_and_extra_columns() {
    let model = ModelSchema::new("users")
        .column(ColumnDef::new("id", "i64").primary_key())
        .column(ColumnDef::new("email", "String").not_null())
        .column(ColumnDef::new("phone", "Option<String>"));

    let existing = vec![
        "id".to_string(),
        "EMAIL".to_string(),
        "legacy_note".to_string(),
    ];

    let (missing, extra) = diff_columns(&model, &existing);

    assert_eq!(
        missing
            .iter()
            .map(|column| column.name.as_str())
            .collect::<Vec<_>>(),
        vec!["phone"]
    );
    assert_eq!(extra, vec!["legacy_note"]);
}

#[test]
fn column_diff_is_empty_when_the_table_matches_the_model() {
    let model = ModelSchema::new("users").column(ColumnDef::new("id", "i64").primary_key());
    let existing = vec!["id".to_string()];

    let (missing, extra) = diff_columns(&model, &existing);

    assert!(missing.is_empty());
    assert!(extra.is_empty());
}
